import {Shell} from "../components";

const works=[
  {slug:"signal",title:"SIGNAL / FINTECH"},
  {slug:"archive",title:"ARCHIVE / CULTURE"},
  {slug:"nexus",title:"NEXUS / AI TOOL"},
  {slug:"mono",title:"MONO / FASHION"},
];

export const caseDetails:Record<string,{title:string,subtitle:string,challenge:string,solution:string,outcome:string}>={
signal:{title:"SIGNAL / FINTECH",subtitle:"Единая система управления личными финансами без визуального давления.",challenge:"Финансовые данные были разбросаны по разным сценариям. Пользователь терял контекст, а ключевые действия конкурировали между собой.",solution:"Мы построили интерфейс вокруг одного финансового потока: единая временная шкала, предсказуемые паттерны и модульная дизайн-система.",outcome:"В результате ключевые сценарии стали короче, интерфейс — спокойнее, а продукт получил масштабируемую основу."},
archive:{title:"ARCHIVE / CULTURE",subtitle:"Цифровой архив, который ощущается как живая выставка.",challenge:"Большой объём разнородных материалов требовал навигации, не превращающей культурный проект в сухую базу данных.",solution:"Редакционная сетка, выразительная типографика и несколько режимов просмотра соединяют исследование и эмоциональное погружение.",outcome:"Архив стал полноценной цифровой экспозицией с ясной логикой и свободным исследованием материалов."},
nexus:{title:"NEXUS / AI TOOL",subtitle:"Сложные AI-процессы в понятном визуальном пространстве.",challenge:"Пользователям было трудно видеть связи между источниками, агентами и результатами работы системы.",solution:"Узловая модель, прозрачные состояния и пошаговое раскрытие сложности делают логику продукта наблюдаемой.",outcome:"Команды быстрее собирают процессы, находят ошибки и понимают, что происходит на каждом этапе."},
mono:{title:"MONO / FASHION",subtitle:"Монохромный магазин, где продукт говорит громче интерфейса.",challenge:"Бренду требовался выразительный e-commerce без конкуренции с коллекциями и кампейн-съёмкой.",solution:"Минимальная навигация, кинематографичные переходы и строгая типографическая система создают спокойный ритм.",outcome:"Покупка стала проще, а цифровая среда — узнаваемой частью идентичности бренда."}};

export function CasePage({slug}:{slug:string}){const p=caseDetails[slug];const current=Math.max(0,works.findIndex(w=>w.slug===slug));const next=works[(current+1)%works.length];return <Shell><section className="case-hero"><div className="kicker">CASE STUDY / 2026</div><h1>{p.title.split(" / ")[0]}<br/><span>{p.title.split(" / ")[1]}</span></h1><p className="case-lead">{p.subtitle}</p><div className="case-facts glass-panel"><p><span>ROLE</span>Art direction<br/>UX/UI design</p><p><span>SCOPE</span>Research<br/>Product system</p><p><span>YEAR / STATUS</span>2026<br/>Completed</p></div></section><section className="case-cover"><div className="case-object"><i/><i/><i/></div><span>01 / HERO VISUAL</span><b className="segment-mark">M2.</b></section><section className="case-copy"><h2>FROM COMPLEXITY<br/>TO CLARITY.</h2><div><span>THE CHALLENGE</span><p>{p.challenge}</p><span>THE SOLUTION</span><p>{p.solution}</p></div></section><section className="process"><div className="process-head"><span>02—PROCESS</span><h2>HOW IT<br/>WAS MADE</h2></div>{[["01","DISCOVERY","Интервью, аудит продукта, карта сценариев и формулировка принципов."],["02","STRUCTURE","Информационная архитектура, пользовательские потоки и быстрые прототипы."],["03","SYSTEM","Типографика, токены, компоненты, состояния и правила поведения."],["04","DELIVERY","Финальные экраны, интерактивный прототип и документация для разработки."]].map(x=><article className="process-step glass-panel" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><section className="case-panels"><div>DISCOVERY<br/><b>01</b></div><div>SYSTEM<br/><b>02</b></div><div>INTERFACE<br/><b>03</b></div></section><section className="outcome"><span>03—OUTCOME</span><blockquote>“{p.outcome}”</blockquote><div><b>24</b><small>CORE SCREENS</small></div><div><b>42</b><small>COMPONENTS</small></div><div><b>01</b><small>COHERENT SYSTEM</small></div></section><a className="next-project interactive" href={`/work/${next.slug}`}><span>NEXT PROJECT</span><strong>{next.title}</strong><b>↗</b></a></Shell>}
