"use client";
import {ArrowIcon,LocalizedShell,SocialLinks} from "../components";

export default function About(){return <LocalizedShell>{ru=><>
  <section className="about-hero"><div className="kicker">02—{ru?"ОБО МНЕ / ПРОФИЛЬ":"ABOUT / PROFILE"}</div><h1>{ru?<>ДЕЛАЮ<br/>СЛОЖНОЕ <span>ЯСНЫМ</span></>:<>MAKING<br/>COMPLEXITY <span>CLEAR</span></>}</h1><p>{ru?"Я — Даниил Черкашин, продуктовый UX/UI-дизайнер с бэкграундом в графике и прикладной информатике. Проектирую веб- и мобильные интерфейсы: от исследования и пользовательских сценариев до адаптивного UI и дизайн-систем.":"I am Daniil Cherkashin, a product UX/UI designer with a background in graphic design and applied informatics. I design web and mobile interfaces from research and user flows to responsive UI and design systems."}</p></section>
  <section className="about-resume"><div><span className="kicker">CV—{ru?"ДВА ПРОФИЛЯ":"TWO PROFILES"}</span><h2>{ru?<>ПРОДУКТОВЫЙ ДИЗАЙН<br/>И ГРАФИКА</>:<>PRODUCT DESIGN<br/>AND GRAPHICS</>}</h2></div><div><p>{ru?"Две версии резюме помогают быстро выбрать нужный фокус: UX/UI и цифровые продукты или графический дизайн и визуальные системы.":"Two résumé versions make it easy to choose the right focus: UX/UI and digital products, or graphic design and visual systems."}</p><a href="/resume">{ru?"ОТКРЫТЬ РЕЗЮМЕ":"OPEN RÉSUMÉ"}<ArrowIcon direction="up-right"/></a></div></section>
  <section className="about-grid"><div><span>01 / {ru?"ПРОФИЛЬ":"BIO"}</span><p>{ru?"Соединяю продуктовую логику с выразительным визуальным языком. Работаю над финансовыми продуктами, веб-сервисами и мобильными интерфейсами; графический дизайн помогает видеть продукт как цельную систему.":"I combine product logic with a distinct visual language. I work on financial products, web services and mobile interfaces; graphic design helps me see a product as one coherent system."}</p><SocialLinks ru={ru} className="about-social-links"/></div><div><span>02 / {ru?"МЕТОДЫ":"METHODS"}</span><ul><li>{ru?"Исследования пользователей":"User research"}</li><li>{ru?"Интервью и опросы":"Interviews & surveys"}</li><li>CJM / User Flows</li><li>{ru?"Информационная архитектура":"Information architecture"}</li><li>{ru?"Анализ конкурентов":"Competitor analysis"}</li><li>{ru?"Тестирование прототипов":"Prototype testing"}</li></ul></div><div><span>03 / {ru?"ИНСТРУМЕНТЫ":"TOOLS"}</span><ul><li>Figma / FigJam</li><li>Miro / Notion</li><li>Photoshop / Illustrator</li><li>After Effects / InDesign</li><li>Tilda / Zero Block</li><li>Blender</li></ul></div><div><span>04 / {ru?"AI-ИНСТРУМЕНТЫ":"AI TOOLS"}</span><ul><li>ChatGPT / Codex</li><li>Claude / Gemini</li><li>Midjourney / Krea</li><li>Runway / Kling</li><li>Meshy / Tripo</li></ul></div></section>
  <section className="experience"><span>{ru?"ОПЫТ":"EXPERIENCE"}</span><div><b>2026—{ru?"СЕЙЧАС":"NOW"}</b><h2>{ru?"EXNODE / UX/UI-ДИЗАЙНЕР":"EXNODE / UX/UI DESIGNER"}</h2><p>{ru?"Адаптивные веб-интерфейсы / дизайн-система / продуктовые и маркетинговые материалы":"Responsive web interfaces / design system / product and marketing assets"}</p></div><div><b>2023—{ru?"СЕЙЧАС":"NOW"}</b><h2>{ru?"НЕЗАВИСИМЫЙ UX/UI-ДИЗАЙНЕР":"INDEPENDENT UX/UI DESIGNER"}</h2><p>{ru?"Сайты / интерфейсы / Tilda / айдентика":"Websites / interfaces / Tilda / visual identity"}</p></div><div><b>2025</b><h2>VK EDUCATION PRACTICE</h2><p>{ru?"Исследование цифрового поведения / концепция социальной сети VK Блик":"Digital behavior research / VK Blik social network concept"}</p></div><div><b>2023</b><h2>SOVA CREATIVE STUDIO</h2><p>{ru?"Личный кабинет студента / user flow / wireframes / UI-макеты":"Student dashboard / user flow / wireframes / UI layouts"}</p></div></section>
  <section className="experience education"><span>{ru?"ОБРАЗОВАНИЕ":"EDUCATION"}</span><div><b>2024—2026</b><h2>{ru?"МИСИС / МАГИСТР":"MISIS / MASTER'S DEGREE"}</h2><p>{ru?"Цифровой брендинг в креативных индустриях":"Digital Branding in Creative Industries"}</p></div><div><b>2020—2024</b><h2>{ru?"МИСИС / БАКАЛАВР":"MISIS / BACHELOR'S DEGREE"}</h2><p>{ru?"Прикладная информатика в дизайне":"Applied Informatics in Design"}</p></div></section>
</>}</LocalizedShell>}
