"use client";
import {LocalizedShell} from "../components";

export default function About(){return <LocalizedShell>{ru=><>
  <section className="about-hero"><div className="kicker">05—{ru?"ОБО МНЕ / ПРОФИЛЬ":"ABOUT / PROFILE"}</div><h1>{ru?<>ДЕЛАЮ<br/>СЛОЖНОЕ <span>ЯСНЫМ.</span></>:<>MAKING<br/>COMPLEXITY <span>CLEAR.</span></>}</h1><p>{ru?"Я — Даниил Черкашин, продуктовый UX/UI-дизайнер и магистрант МИСИС. Исследую поведение пользователей и проектирую понятные системы для сложных цифровых продуктов.":"I am Daniil Cherkashin, a product UX/UI designer and MISIS master's student. I research user behavior and design clear systems for complex digital products."}</p></section>
  <section className="about-grid"><div><span>01 / {ru?"ПРОФИЛЬ":"BIO"}</span><p>{ru?"Работаю с финансовыми и криптопродуктами, насыщенными данными интерфейсами, лендингами и веб-приложениями Telegram.":"I work with financial and crypto products, data-heavy interfaces, landing pages and Telegram Web Apps."}</p></div><div><span>02 / {ru?"МЕТОДЫ":"METHODS"}</span><ul><li>{ru?"Исследования пользователей":"User research"}</li><li>{ru?"Интервью и опросы":"Interviews & surveys"}</li><li>CJM / User Flows</li><li>{ru?"Информационная архитектура":"Information architecture"}</li><li>{ru?"Анализ конкурентов":"Competitor analysis"}</li><li>{ru?"Юзабилити-тестирование":"Usability testing"}</li></ul></div><div><span>03 / {ru?"ИНСТРУМЕНТЫ":"TOOLS"}</span><ul><li>Figma / FigJam</li><li>Miro / Notion</li><li>Adobe CC</li><li>Tilda / Zero Block</li><li>HTML / CSS</li><li>Blender</li></ul></div></section>
  <section className="experience"><span>{ru?"ОПЫТ":"EXPERIENCE"}</span><div><b>2025—{ru?"СЕЙЧАС":"NOW"}</b><h2>{ru?"EXNODE / ПРОДУКТОВЫЙ ДИЗАЙНЕР":"EXNODE / PRODUCT DESIGNER"}</h2><p>{ru?"Финансовая платформа / сложные данные / дизайн-система":"Financial platform / complex data / design system"}</p></div><div><b>2023—{ru?"СЕЙЧАС":"NOW"}</b><h2>{ru?"НЕЗАВИСИМЫЙ UX/UI-ДИЗАЙНЕР":"INDEPENDENT UX/UI DESIGNER"}</h2><p>{ru?"Сайты / интерфейсы / веб-приложения Telegram":"Websites / interfaces / Telegram Web Apps"}</p></div></section>
  <section className="experience education"><span>{ru?"ОБРАЗОВАНИЕ":"EDUCATION"}</span><div><b>2024—2026</b><h2>{ru?"МИСИС / МАГИСТРАТУРА":"MISIS / MASTER'S"}</h2><p>{ru?"Цифровой брендинг в креативных индустриях":"Digital Branding in Creative Industries"}</p></div><div><b>2020—2024</b><h2>{ru?"МИСИС / БАКАЛАВРИАТ":"MISIS / BACHELOR'S"}</h2><p>{ru?"Прикладная информатика в дизайне":"Applied Informatics in Design"}</p></div></section>
</>}</LocalizedShell>}
